title: Sanjay Mehra # your name (or website title) here
logo: "/images/instasize_190410160202.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspirant As Software Engineer 
  <br><br>
  Be Happy
  <br><br>
  <a href="https://www.linkedin.com/in/sanjay-mehra-835816152/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
