title: Sanjay Mehra # your name (or website title) here
logo: "/images/instasize_190410160202.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <p><b>Aspirant As Software Engineer</b></p> 
  <br><br>
  <p><b> Email - mehra271198@gmail.com </b></p>
  <br><br>
  <a href="https://www.linkedin.com/in/sanjay-mehra-835816152/"> - LinkedIn Profile </a>
  <br><br>
  <a href="https://www.hackerrank.com/mehra271198"> - HackerRank Profile </a>
  <br><br>
  <a href="https://github.com/Me-SanjayMehra-27"> - GitHub Profile </a>
   <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
