title: AKASH KUMAR # your name (or website title) here
logo: "/images/IMG_20181215_121005_225.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <p><b> Email - me.akashkumar47@gmail.com
  </b> </p>
  <p><b> Contact - 9079218773
  </b> </p>
  
  <br><br>
  <a href="https://www.linkedin.com/in/akash-kumar-b9b810152/"> - LinkedIn Profile </a>
  <br><br>
  <a href="https://github.com/AkashVerma47"> - GitHub Profile </a>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
